# -*- coding: utf-8 -*-
"""Finance_Data_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14kqXPZCa0aD7gsZyAzzuVDFoWnVELN39
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style('darkgrid')

"""### Load dataset

"""

df = pd.read_csv("Finance_data.csv")

df.head()

df.drop(['Mutual_Funds', 'Equity_Market',
       'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold'],axis=1,inplace=True)

# First we will see Gender of our respondenets
sns.countplot(df['gender'],linewidth=3,palette="Set2",edgecolor='black')
plt.show()

# Now we will see Age of our respondents
sns.countplot(df['age'],palette="Set3",linewidth=2,edgecolor='black')
plt.show()

"""We can see from the above graph that most of our respondents were in the ages 24-31 and we will look further their habits in the finanace field"""

# Now lets see these same factors of INVESTMENT_AVENUE and STOCK_MARKET with gender

plt.figure(figsize=(18,6))
plt.subplot(1, 2, 1)
sns.countplot(x=df['gender'],hue=df['Investment_Avenues'],palette='summer',linewidth=3,edgecolor='white')
plt.title('INVESTMENT AVENUE')
plt.subplot(1, 2, 2)
sns.countplot(x=df['gender'],hue=df['Stock_Marktet'],palette='hot',linewidth=3,edgecolor='white')
plt.title('STOCK MARKET')
plt.show()


# Mostly females dont invest or go to stocks

# Factors affecting Investing 
sns.countplot(x=df['Factor'],palette='coolwarm',linewidth=2,edgecolor='black')

# Returns is the most influential Factor considered while investing which is followed by risk

"""The above trend shows us that people are less worried about risks involved and more worried about the money which they will get back


"""

# Lets see which Age groups take the highest risk 
sns.countplot(x=df['gender'],hue=df['Factor'],palette='Oranges',linewidth=2,edgecolor='black')
plt.title('Gender')
plt.show()

"""We can see that high number of males are dependent on Returns


"""

plt.figure(figsize=(16,6))
sns.pointplot(x="Purpose",y='age',data=df,linestyles="--",capsize=.3,color='Red')
plt.show()

"""From the above plot it is clear that as people grow older they are more inclined towards Returns and people at young age look more for wealth creation


"""

# Now lets see these same factors of Duration and Invest_monitor with gender

plt.figure(figsize=(18,6))
plt.subplot(1, 2, 1)
sns.countplot(hue=df['gender'],x=df['Duration'],palette='viridis',linewidth=2,edgecolor='black')
plt.title('DURATION')
plt.subplot(1, 2, 2)
sns.countplot(hue=df['gender'],x=df['Invest_Monitor'],palette='seismic',linewidth=2,edgecolor='black')
plt.title('INVESTMENT MONITORING')
plt.show()

#Below graphs show us that most of the people invest from 1-5 Years and monitor their investments mostly monthly